from setuptools import setup, find_packages

setup(
    name="xss-sentinel",
    version="2.0.0",
    description="Advanced AI-Powered XSS Testing Platform",
    author="NOTTIBOY137",
    author_email="",
    url="https://github.com/NOTTIBOY137/xss-sentinel",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "requests>=2.28.1",
        "beautifulsoup4>=4.11.1",
        "scikit-learn>=1.1.2",
        "numpy>=1.23.2",
        "tqdm>=4.64.0",
        "colorama>=0.4.5",
        "joblib>=1.1.0",
        "lxml>=4.9.0",
        "selenium>=4.0.0",
        "fake-useragent>=1.1.0",
        "cloudscraper>=1.2.0",
        "undetected-chromedriver>=3.5.0",
        "requests-html>=0.10.0",
        "aiohttp>=3.8.0",
        "asyncio-throttle>=1.0.0",
        "python-whois>=0.8.0",
        "dnspython>=2.3.0",
        "cryptography>=3.4.0",
        "pycryptodome>=3.15.0",
        "urllib3>=1.26.0",
        "playwright>=1.40.0",
    ],
    extras_require={
        "ai": [
            "sentence-transformers>=2.2.0",
            "transformers>=4.20.0",
            "torch>=1.12.0",
        ],
        "dev": [
            "pytest>=7.0.0",
            "flake8>=5.0.0",
            "black>=22.0.0",
        ],
    },
    entry_points={
        'console_scripts': [
            'xss-sentinel=xss_sentinel.cli:main',
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Security",
        "Topic :: Internet :: WWW/HTTP",
    ],
    python_requires=">=3.8",
)
